name: $(BuildDefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - dev

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'Build'
    displayName: 'Build'
    jobs:
      - job: 'build'
        displayName: 'Build artifacts'
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '16.10.0'

          - script: |
              npm install -g @angular/cli nx
              npm install --force 
              npm install copyfiles -g
              npm i -D shx 
            displayName: 'install dependencies'

          - script: npm run buildAll
            displayName: 'Build app for dev'

#          - script: npm run buildINT
#            displayName: 'Build app for int'

          #- task: HCLAppScanOnCloud@2
          #  displayName: 'AppScan Vulnerability Scan'
          #  inputs:
          #    AppSecTestService: 'appscanforcompass'
          #    applications: 'e07e1354-de45-4412-9f8f-c09b95e067d7'
          #    scanname: 'compass ui sast scan'
          #    scantype: 'static'
