parameters:
- name: 'environment'
- name: 'artifactname'
- name: 'branch'
- name: 'pipeline'
- name: 'runid'
- name: 'runversion'
- name: 'storageaccount'
- name: 'azuresubscription'
#- name: 'appmodule'

steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: DHS Modernized Applications 
      pipeline: ${{ parameters.pipeline }}
      runVersion: specific
      runBranch: 'refs/heads/${{ parameters.branch }}'
      runId: '${{ parameters.runid }}'
      artifact: ${{ parameters.artifactname }}
      path: '$(Pipeline.Workspace)/${{ parameters.artifactname }}'

  - task: AzureCLI@2
    displayName: 'Add IP to Firewall'
    inputs:
      azureSubscription: '${{ parameters.azuresubscription }}'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        export ipaddr="$(curl -s ipinfo.io/json | jq -r '.ip')"
        echo "Opening Firewall: $ipaddr"
        echo "##vso[task.setvariable variable=ipaddr;isOutput=true]$ipaddr"
        az config set extension.use_dynamic_install=yes_without_prompt
        az storage account network-rule add --account-name ${{ parameters.storageaccount }} --ip-address $ipaddr
        sleep 10s
      addSpnToEnvironment: true

  - task: AzureCLI@2
    displayName: 'Clear Static website'
    inputs:
      azureSubscription: '${{ parameters.azuresubscription }}'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az storage blob delete-batch --account-name ${{ parameters.storageaccount }} --source "\$web"'
      addSpnToEnvironment: true

  - task: AzureCLI@2
    displayName: 'Upload new Static Website'
    inputs:
      azureSubscription: '${{ parameters.azuresubscription }}'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az storage blob upload-batch --account-name ${{ parameters.storageaccount }} --destination "\$web" --source ''$(Pipeline.Workspace)/${{ parameters.artifactname }}'''
      addSpnToEnvironment: true

  - task: AzureCLI@2
    displayName: 'Remove IP from Firewall'
    condition: always()
    inputs:
      azureSubscription: '${{ parameters.azuresubscription }}'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        export ipaddr="$(curl -s ipinfo.io/json | jq -r '.ip')"
        echo "Closing Firewall: $ipaddr"
        echo "##vso[task.setvariable variable=ipaddr;isOutput=true]$ipaddr"
        az config set extension.use_dynamic_install=yes_without_prompt
        az storage account network-rule remove --account-name ${{ parameters.storageaccount }} --ip-address $ipaddr
      addSpnToEnvironment: true
