export const INDIVIDUAL_PROGRAMS = {
    HC: "HC",
    HA: "HA",
    CA: "CA",
    FS: "FS",
    FSR: "FSR",
    CAR: "CAR",
    CHR: "CHR",
    ABR: "ABR",
    BL: "BL",
    MAR: "MAR",
    MCR: "MCR",
    MI: "MI",
    CI: "CI",
	CR: "CR",
    CIR: "CIR",
    ES: "ES",
    ESR: "ESR",
    FP: "FP",
    FPR:"FPR",
    PE: "PE",
    ECA: "ECA",
    WN: "WN",
    WNR: "WNR",
    LI: "LI",
    LIR: "LIR",
    LN:"LN",
    LNR: "LNR",
    WAR: "WAR",
    SMA: "SMA",
    LW: "LW",
    LH: "LH",
    LHP:"LHP",
    LHCR:"LHCR"

}
export const REQUIREDOPTIONALCONTSTANTS =
{
    REQ: 'Required',
    OPT: 'Optional',
    NULL: null
}

export const IND_BENEFITNOTRECEIVED_DETAIL_CONDITIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR]
export const IND_BENEFITNOTRECEIVED_DETAIL_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR]
export const IND_FAMILYPLANNING_REVIEW_CONDITIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR]
export const IND_FAMILYPLANNING_REVIEW_REQUIREDPROGRAMS = []
export const IND_SSI__REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.HA];
export const IND_SSI_CONDITIONALPROGRAMS = []
export const IND_CURRENTEDUCATION_SCHOOLNAME_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR]
export const IND_CURRENTEDUCATION_SCHOOLNAME_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_CURRENTEDUCATION_SCHOOLTYPE_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR]
export const IND_CURRENTEDUCATION_SCHOOLTYPE_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_CURRENTEDUCATION_ATTENDSCHOOLE_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR]
export const IND_CURRENTEDUCATION_ATTENDSCHOOLE_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_CURRENTEDUCATION_EXPECTGRADUATE_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_MEDICALCONDITION_MEDICALCONDITION_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.ESR]
export const IND_MEDICALCONDITION_MEDICALCONDITION_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.MI]
export const IND_MEDICALCONDITION_BEGINDATE_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_MEDICALCONDITION_DISABILITY_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_MEDICALCONDITION_ABLETOWORK_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_MEDICALCONDITION_CARECHILDREN_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_MEDICALCONDITION_SSI_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_MEDICALCONDITION_CHILDDISABILITY_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_MEDICALCONDITION_DEVELOPMENTAGE_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_INCARCERATION_COUNTYOFPLACEMENT_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.SMA]
export const IND_INCARCERATION_INCARCERATIONADMISSIONDATE_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.SMA]
export const IND_INCARCERATION_INCARCERATIONRELEASEDATE_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR]
export const IND_INCARCERATION_INCARCERATIONRELEASEDATE_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.MI]

export const IND_PREGNANCYDETAILS_BABIESREQUIRED_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.ECA]
export const IND_RECEIVEDLONGTERMDETAILS_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR]
export const IND_TAX_DEPENDENT_DETAILS_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.MI]
export const IND_FILING_JOINTLY_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.MI]
export const IND_CLAIM_TAX_DEPENDENT_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.MI]
export const IND_PREGNANCYDETAILS_PREGNANCYDUE_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.ECA]

export const IND_BURIAL_TRUST_DETAILS_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR]
export const IND_BURIAL_TRUST_ADDITIONAL_DETAILS_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR]
export const IND_BURIAL_TRUST_DETAILS_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR]

export const IND_FEDERAL_TRIBE_INFO_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR]
export const IND_FEDERAL_TRIBE_INCOME_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR]
export const IND_FEDERAL_TRIBE_INCOME_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR]
export const IND_TRAINING_DETAIL_INSTITUTENAME_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_TRAINING_DETAIL_STARTDATE_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_TRAINING_DETAIL_FINISHPROGRAM_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_TRAINING_DETAIL_HOURSWEEK_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR]
export const IND_ADDITIONAL_DETAIL_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR]
export const IND_ADDITIONAL_DETAIL_SUFFIX_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR]
export const IND_ADDITIONAL_DETAIL_RELATIONSHIP_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR]
export const IND_ADDITIONAL_DETAIL_PERSONROLE_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR]
export const IND_ADDITIONAL_DETAIL_CONTACT_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR]
export const IND_ADDITIONAL_DETAIL_DOB_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.WAR]
export const IND_DETAIL_MILATARYBOS_REQUIREDPROGRAMS = [INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR]
export const IND_DETAIL_MILATARYBOS_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR];
export const IND_DETAIL_MILATARYDE_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR];
export const IND_DETAIL_MILATARYDD_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR]
export const IND_DETAIL_MILATARYVCN_OPTIONALPROGRAMS = [INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR]
export const IND_PRIMARY_CARE = [INDIVIDUAL_PROGRAMS.HC];
export const IND_FOSTER_CARE = [ INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR
  , INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.MI]
export const IND_FOSTER_CHILD= [INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CHR]
export const IND_FOSTER_ADULT = [
    INDIVIDUAL_PROGRAMS.HA,
    INDIVIDUAL_PROGRAMS.HC,
    INDIVIDUAL_PROGRAMS.MAR,
    INDIVIDUAL_PROGRAMS.MCR,
    INDIVIDUAL_PROGRAMS.CA,
    INDIVIDUAL_PROGRAMS.CAR,
    INDIVIDUAL_PROGRAMS.FP,
    INDIVIDUAL_PROGRAMS.FPR,
    INDIVIDUAL_PROGRAMS.PE,
    INDIVIDUAL_PROGRAMS.MI,
];
export const IND_CHILD_CARE = [
    INDIVIDUAL_PROGRAMS.CI,
    INDIVIDUAL_PROGRAMS.CIR,
    INDIVIDUAL_PROGRAMS.CHR,
    INDIVIDUAL_PROGRAMS.ABR,
];
export const IND_GEN_DETAIL_CITIZENSHIP_REQUIRED_PROGRAMS = [INDIVIDUAL_PROGRAMS.HA, 
    INDIVIDUAL_PROGRAMS.ABR,INDIVIDUAL_PROGRAMS.HC, 
    INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LN,
    INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LNR,
     INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP,
    INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.LIR, 
    INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR,
    INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE,
     INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR,
    INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.SMA, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW
 ];
export const IND_GEN_DETAIL_CITIZENSHIP_OPTIONAL_PROGRAMS = [INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.ESR, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR]
export const IND_GEN_DETAIL_MARITALSTATUS_REQUIRED_PROGRAMS = [INDIVIDUAL_PROGRAMS.HA,
    INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.HC,
    INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LN,
    INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LNR,
    INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP,
    INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.LIR,
    INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR,
    INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE,
    INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR,
    INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.SMA, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR];
export const IND_GEN_DETAIL_MARITALSTATUS_OPTIONAL_PROGRAMS = [INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.ESR];
export const IND_GEN_DETAIL_SPOUSENAME_OPTIONAL_PROGRAMS = [INDIVIDUAL_PROGRAMS.HA,
    INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.HC,
    INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LN,
    INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LNR,
    INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP,
    INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.LIR,
    INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR,
    INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE,
    INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR,
    INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.SMA, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MCR];
export const IND_GEN_DETAIL_DOD_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LNR];
export const IND_GEN_DETAIL_DOS_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.LN,INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR];
export const IND_GEN_DETAIL_GRAD_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR];
export const IND_GEN_DETAIL_GRAD_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.CI];
export const IND_GEN_DETAIL_RUNAWAY_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.BL];
export const IND_CITIZENSHIP_DETAIL_COUNTRY_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MCR,
    INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.HA,
    INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.ABR,
    INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS,
    INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.ESR, INDIVIDUAL_PROGRAMS.FSR,
    INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI,
    INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR,
    INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI];
export const IND_CITIZENSHIP_DETAIL_COUNTRYFROM_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MCR,
INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.HA,
INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.ABR,
INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR,
INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI,
INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR,
INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI];
export const IND_CITIZENSHIP_DETAIL_DOC_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MCR,
INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.HA,
    INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.MI,
 INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.ESR,
INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR];
export const IND_CITIZENSHIP_DETAIL_SPONSOR_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA,
INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LN,
INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI,
INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.FP,
    INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR];

export const HOU_ADDRESS_VALIDATION_ADDRESS1_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.LW, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ESR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.SMA, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_ADDRESS_VALIDATION_ADDRESS2_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.LW, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ESR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.SMA, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_ADDRESS_VALIDATION_CITY_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.LW, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ESR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.SMA, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_ADDRESS_VALIDATION_STATE_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.LW, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ESR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.SMA, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_ADDRESS_VALIDATION_ZIP_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.LW, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ESR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.SMA, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_ADDRESS_VALIDATION_COUNTY_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.LW, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ESR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.SMA, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_ADDRESS_VALIDATION_SCHOOL_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_ADDRESS_VALIDATION_SCHOOL_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.FS];
export const HOU_ADDRESS_VALIDATION_TOWNSHIP_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.MI];
export const HOU_ADDRESS_VALIDATION_TOWNSHIP_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_ADDRESS_VALIDATION_TOWNSHIP1_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_ADDRESS_VALIDATION_ADDANOTHER_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.LW, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ESR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.SMA, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_ADDRESS_VALIDATION_HOWLONG_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR];

export const HOU_CURRENT_HOUSING_SITUATION_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LW, INDIVIDUAL_PROGRAMS.LHCR];
export const HOU_CURRENT_HOUSING_OTHER_SITUATION_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LW];

export const INCOME_CURRENTJOB_ISSELFEMPLOYMENT_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR];
export const INCOME_CURRENTJOB_EMPLOYERNAME_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW];
export const INCOME_CURRENTJOB_EMPLOYERNAME_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR];
export const INCOME_CURRENTJOB_STREETADDRESS1_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW];
export const INCOME_CURRENTJOB_STREETADDRESS2_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW];
export const INCOME_CURRENTJOB_CITY_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.ECA];
export const INCOME_CURRENTJOB_STATE_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.ECA];
export const INCOME_CURRENTJOB_STATE_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.LW];
export const INCOME_CURRENTJOB_ZIP_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW];
export const INCOME_CURRENTJOB_PHONE_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW];

export const HOU_PREVIOUS_ADDRESS_ADDRESS_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_PREVIOUS_ADDRESS_ADDRESS2_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_PREVIOUS_ADDRESS_CITY_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_PREVIOUS_ADDRESS_STATE_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_PREVIOUS_ADDRESS_ZIP_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_PREVIOUS_ADDRESS_PHONE_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.ECA];

export const HOU_LIVING_SITUATION_LIVING_OPTIONAL_PROGRAMS = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR];
export const HOU_LIVING_SITUATION_EFFDATE_OPTIONAL_PROGRAMS = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI];

export const HOU_CONTACT_INFO_MAIN_OPTIONAL_PROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW];
export const HOU_CONTACT_INFO_SECONDARY_OPTIONAL_PROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW];
export const HOU_CONTACT_INFO_OTHER_OPTIONAL_PROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW];
export const HOU_CONTACT_INFO_EMAIL_OPTIONAL_PROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_CONTACT_INFO_CONFIRMEMAIL_OPTIONAL_PROGRAMS = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_CONTACT_INFO_CONTACT_OPTIONAL_PROGRAMS = [INDIVIDUAL_PROGRAMS.HC];
export const HOU_CONTACT_INFO_CONTACT_REQUIRED_PROGRAMS = [INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR];

export const HOU_APPLIED_BEFORE_STATE_REQUIRED_PROGRAMS = [INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.ECA];
export const HOU_APPLIED_BEFORE_COUNTY_OPTIONAL_PROGRAMS = [INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.ECA];

export const INCOME_OTHERINCOMEDETAILS_INCOMETYPE_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP,INDIVIDUAL_PROGRAMS.CR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR,  INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW ];
export const INCOME_OTHERINCOMEDETAILS_INCOMETYPE_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.ESR];
export const INCOME_OTHERINCOMEDETAILS_OTHERINCOMEDESCRIPTION_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.CR, INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ESR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW ];
export const INCOME_OTHERINCOMEDETAILS_FREQUENCY_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.CR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW];
export const INCOME_OTHERINCOMEDETAILS_FREQUENCY_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.ESR];
export const INCOME_OTHERINCOMEDETAILS_GROSSINCOME_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.CR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW];
export const INCOME_OTHERINCOMEDETAILS_GROSSINCOME_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.ESR];
export const INCOME_OTHERINCOMEDETAILS_MOSTRECENTPAYDATE_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW];
export const INCOME_OTHERINCOMEDETAILS_MOSTRECENTPAYDATE_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.FS, INDIVIDUAL_PROGRAMS.FSR, INDIVIDUAL_PROGRAMS.ES, INDIVIDUAL_PROGRAMS.ESR];

export const INCOME_OTHERINCOMEADDRESS_ISDIFFERENTADDRESS_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.WN];
export const INCOME_OTHERINCOMEADDRESS_NAMEOFFINANCIALINSTITUTION_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR];
export const INCOME_OTHERINCOMEADDRESS_ADDRESSLINE1_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR];
export const INCOME_OTHERINCOMEADDRESS_ADDRESSLINE2_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR];
export const INCOME_OTHERINCOMEADDRESS_CITY_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR];
export const INCOME_OTHERINCOMEADDRESS_STATE_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR];
export const INCOME_OTHERINCOMEADDRESS_ZIP_OPTIONAL_PROGRAM = [INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR];
export const INCOME_OTHERINCOMEENDMODAL_DATEOFLASTPAY_REQUIRED_PROGRAM = [INDIVIDUAL_PROGRAMS.HC, INDIVIDUAL_PROGRAMS.HA, INDIVIDUAL_PROGRAMS.MCR, INDIVIDUAL_PROGRAMS.MAR, INDIVIDUAL_PROGRAMS.CHR, INDIVIDUAL_PROGRAMS.ABR, INDIVIDUAL_PROGRAMS.CA, INDIVIDUAL_PROGRAMS.CAR, INDIVIDUAL_PROGRAMS.LN, INDIVIDUAL_PROGRAMS.LNR, INDIVIDUAL_PROGRAMS.LI, INDIVIDUAL_PROGRAMS.LIR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.LHCR, INDIVIDUAL_PROGRAMS.CI, INDIVIDUAL_PROGRAMS.CIR, INDIVIDUAL_PROGRAMS.BL, INDIVIDUAL_PROGRAMS.FP, INDIVIDUAL_PROGRAMS.FPR, INDIVIDUAL_PROGRAMS.LH, INDIVIDUAL_PROGRAMS.LHP, INDIVIDUAL_PROGRAMS.CR, INDIVIDUAL_PROGRAMS.PE, INDIVIDUAL_PROGRAMS.WN, INDIVIDUAL_PROGRAMS.WNR, INDIVIDUAL_PROGRAMS.WAR, INDIVIDUAL_PROGRAMS.MI, INDIVIDUAL_PROGRAMS.ECA, INDIVIDUAL_PROGRAMS.LW];
export const INCOME_NOINCOME_NOINCOMEEXPLANATION_REQUIRED_PROGRAM =[INDIVIDUAL_PROGRAMS.BL];